# We use Alacritty's default Linux config directory as our storage location here.
#mkdir -p ~/.config/alacritty/themes
#git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes

import = [
    "~/.config/alacritty/themes/themes/hyper.toml"
]

[font]
size = 10.0

[scrolling]
history = 10000
multiplier = 3

[window.dimensions]
columns = 80
lines = 24
